application: gopherpods
runtime: go
api_version: go1
version: beta-1

env_variables:
  EMAIL: 'mail@mail.com'
  SECRET: 'reCAPTCHA secret key'

handlers:

- url: /css
  static_dir: static/css

- url: /submit
  script: _go_app
  secure: always

- url: /submit/add
  script: _go_app
  secure: always

- url: /feed
  script: _go_app
  secure: always

- url: /submissions
  script: _go_app
  login: admin
  secure: always

- url: /submissions/add
  script: _go_app
  login: admin
  secure: always

- url: /submissions/del
  script: _go_app
  login: admin
  secure: always

- url: /tasks/email
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always