application: gopherpods
runtime: go
api_version: go1
version: beta-1

handlers:

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /submit/.*
  script: _go_app
  secure: always

- url: /submissions/.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always